## Assignment 1: NumPy Arrays and Matrix Operations

Objective

Practice using NumPy to create and manipulate multidimensional arrays and perform mathematical and linear-algebra operations.

This assignment is based on the NumPy concepts demonstrated in class: array creation, array properties, slicing, Boolean indexing, element-wise operations, matrix multiplication, transpose, and axis operations.

Instructions

Complete all problems using NumPy. Do not use Python lists for the mathematical operations.
Submit a Jupyter Notebook containing:

* Your Python code
* The output of each problem
* Short answers to the questions
* Clear comments explaining your code

---
#### Part 1 — Creating and Inspecting Arrays

1.	Create the following NumPy array:
```python
 	[[10, 20, 30, 40],
 [50, 60, 70, 80],
 [90, 100, 110, 120]]
```

In [5]:
%pip install numpy

import numpy as np

# Rows and columns are stored in a NumPy array.
array = np.array([[10, 20, 30, 40],
                  [50, 60, 70, 80],
                  [90, 100, 110, 120]])
print(array)


Note: you may need to restart the kernel to use updated packages.
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


2.	Print:
* The array
* Its type
* Shape
* Number of elements
* Number of dimensions
* Data type

In [6]:
print("Array:\n", array)
print("Type:", type(array))
print("Shape:", array.shape)
print("Number of elements:", array.size)
print("Number of dimensions:", array.ndim)
print("Data type:", array.dtype)


Array:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
Type: <class 'numpy.ndarray'>
Shape: (3, 4)
Number of elements: 12
Number of dimensions: 2
Data type: int64


3.	Create:
* A 3 × 4 array of zeros
* A 2 × 5 array of ones
* A 4 × 4 identity matrix
* A 3 × 3 array of random numbers between 0 and 1

In [ ]:
rng = np.random.default_rng(42)
print("3 x 4 zeros:\n", np.zeros((3, 4)))
print("2 x 5 ones:\n", np.ones((2, 5)))
print("4 x 4 identity:\n", np.eye(4))
print("3 x 3 random values in [0, 1):\n", rng.random((3, 3)))


3 x 4 zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2 x 5 ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
4 x 4 identity:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
3 x 3 random values in [0, 1):
 [[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]
 [0.7611397  0.78606431 0.12811363]]


---
## Part 2 — Indexing and Slicing

Using the array from Part 1:

1.	Extract the value 70.
2.	Extract the first row.
3.	Extract the last row.
4.	Extract the second column.
5.	Extract the first three columns.
6.	Extract the last two rows.
7.	Extract every other element from the second row.
8.	Extract the following submatrix:
```python 	
    [[60, 70],
 [100, 110]]
 ```


In [ ]:
print("1. Value 70:", array[1, 2])
print("2. First row:", array[0, :])
print("3. Last row:", array[-1, :])
print("4. Second column:", array[:, 1])
print("5. First three columns:\n", array[:, :3])
print("6. Last two rows:\n", array[-2:, :])
print("7. Every other element of second row:", array[1, ::2])
print("8. Submatrix:\n", array[1:3, 1:3])


1. Value 70: 70
2. First row: [10 20 30 40]
3. Last row: [ 90 100 110 120]
4. Second column: [ 20  60 100]
5. First three columns:
 [[ 10  20  30]
 [ 50  60  70]
 [ 90 100 110]]
6. Last two rows:
 [[ 50  60  70  80]
 [ 90 100 110 120]]
7. Every other element of second row: [50 70]
8. Submatrix:
 [[ 60  70]
 [100 110]]


---
## Part 3 — Boolean Indexing

Create:
```python
x = np.array([[12, 5, 18, 3],
              [25, 7, 14, 9],
              [2, 30, 11, 20]])
```
1.	Extract all values greater than 15.
2.	Extract all values less than or equal to 10.
3.	Replace every value greater than 20 with 0.
4.	Count how many values are greater than 15.

In [9]:
x = np.array([[12, 5, 18, 3],
              [25, 7, 14, 9],
              [2, 30, 11, 20]])
print("1. Values greater than 15:", x[x > 15])
print("2. Values at most 10:", x[x <= 10])
original_count = np.count_nonzero(x > 15)

x[x > 20] = 0
print("3. After replacing values greater than 20:\n", x)
print("4. Count greater than 15 after replacement:", np.count_nonzero(x > 15))
print("Count greater than 15 in the original array:", original_count)


1. Values greater than 15: [18 25 30 20]
2. Values at most 10: [5 3 7 9 2]
3. After replacing values greater than 20:
 [[12  5 18  3]
 [ 0  7 14  9]
 [ 2  0 11 20]]
4. Count greater than 15 after replacement: 2
Count greater than 15 in the original array: 4


---
## Part 4 — Element-Wise Arithmetic
Create:
```python
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])
```
Calculate:
1.	A + B
2.	A - B
3.	A * B
4.	A / B
5.	A ** 2
6.	np.sqrt(A)

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("1. A + B:\n", A + B)
print("2. A - B:\n", A - B)
print("3. A * B:\n", A * B)
print("4. A / B:\n", A / B)
print("5. A ** 2:\n", A ** 2)
print("6. Square root of A:\n", np.sqrt(A))


1. A + B:
 [[ 6  8]
 [10 12]]
2. A - B:
 [[-4 -4]
 [-4 -4]]
3. A * B:
 [[ 5 12]
 [21 32]]
4. A / B:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
5. A ** 2:
 [[ 1  4]
 [ 9 16]]
6. Square root of A:
 [[1.         1.41421356]
 [1.73205081 2.        ]]


---
## Part 5 — Matrix Multiplication
Create:
```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
```
1.	Compute A @ B.
2.	Compute the same result using np.dot(A, B).
3.	Verify that both results are identical.
4.	Print the shape of A, B, and the result.

The notebook demonstrates the equivalence of .dot(), np.dot(), and @ for matrix multiplication.

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
product = A @ B
product_dot = np.dot(A, B)
print("1. A @ B:\n", product)
print("2. np.dot(A, B):\n", product_dot)
print("3. Results identical:", np.array_equal(product, product_dot))
print("A.dot(B) also matches:", np.array_equal(product, A.dot(B)))
print("4. Shapes: A =", A.shape, "B =", B.shape, "result =", product.shape)


1. A @ B:
 [[ 58  64]
 [139 154]]
2. np.dot(A, B):
 [[ 58  64]
 [139 154]]
3. Results identical: True
A.dot(B) also matches: True
4. Shapes: A = (2, 3) B = (3, 2) result = (2, 2)


---
## Part 6 — Transpose and Axis Operations
Using:
```python
X = np.array([[2, 4, 6],
              [8, 10, 12]])
```
Calculate:
1.	X.T
2.	np.transpose(X)
3.	np.sum(X)
4.	np.sum(X, axis=0)
5.	np.sum(X, axis=1)
6.	np.mean(X)
7.	np.mean(X, axis=0)
8.	np.mean(X, axis=1)
9.	np.max(X, axis=0)
10.	np.min(X, axis=1)
11.	np.std(X)

For each axis operation, write one sentence explaining what the axis represents.

Axis explanations:

- `np.sum(X, axis=0)` adds down the rows, giving one sum for each column.
- `np.sum(X, axis=1)` adds across the columns, giving one sum for each row.
- `np.mean(X, axis=0)` averages down the rows, giving one mean for each column.
- `np.mean(X, axis=1)` averages across the columns, giving one mean for each row.
- `np.max(X, axis=0)` finds the largest entry down the rows in each column.
- `np.min(X, axis=1)` finds the smallest entry across the columns in each row.
- With no axis specified, sum, mean, and standard deviation use all elements.


In [12]:
X = np.array([[2, 4, 6], [8, 10, 12]])
print("1. X.T:\n", X.T)
print("2. np.transpose(X):\n", np.transpose(X))
print("3. Total sum:", np.sum(X))
print("4. Column sums:", np.sum(X, axis=0))
print("5. Row sums:", np.sum(X, axis=1))
print("6. Overall mean:", np.mean(X))
print("7. Column means:", np.mean(X, axis=0))
print("8. Row means:", np.mean(X, axis=1))
print("9. Column maxima:", np.max(X, axis=0))
print("10. Row minima:", np.min(X, axis=1))
print("11. Overall standard deviation:", np.std(X))


1. X.T:
 [[ 2  8]
 [ 4 10]
 [ 6 12]]
2. np.transpose(X):
 [[ 2  8]
 [ 4 10]
 [ 6 12]]
3. Total sum: 42
4. Column sums: [10 14 18]
5. Row sums: [12 30]
6. Overall mean: 7.0
7. Column means: [5. 7. 9.]
8. Row means: [ 4. 10.]
9. Column maxima: [ 8 10 12]
10. Row minima: [2 8]
11. Overall standard deviation: 3.415650255319866


---
## Part 7 — Mini Application: Student Grades

Create a NumPy array containing the grades of 5 students in 4 assignments:

* Student 1: 85, 90, 78, 92
* Student 2: 70, 88, 91, 76
* Student 3: 95, 93, 89, 97
* Student 4: 60, 72, 68, 75
* Student 5: 88, 84, 90, 86

Using NumPy only:
1.	Calculate each student’s average.
2.	Find the highest grade on each assignment.
3.	Find the average grade for each assignment.
4.	Find the student with the highest overall average.
5.	Find all grades below 70.
6.	Replace grades below 70 with 70.
7.	Calculate the overall class average.

In [13]:
grades = np.array([[85, 90, 78, 92],
                   [70, 88, 91, 76],
                   [95, 93, 89, 97],
                   [60, 72, 68, 75],
                   [88, 84, 90, 86]])
student_averages = np.mean(grades, axis=1)
print("1. Student averages:", student_averages)
print("2. Highest grade per assignment:", np.max(grades, axis=0))
print("3. Average per assignment:", np.mean(grades, axis=0))
best_student = np.argmax(student_averages) + 1
print("4. Student with highest average:", best_student)
print("Highest average:", np.max(student_averages))
print("5. Grades below 70:", grades[grades < 70])
original_class_average = np.mean(grades)
# Apply the requested minimum grade before calculating step 7.
grades[grades < 70] = 70
print("6. Grades after replacement:\n", grades)
print("7. Overall class average after replacement:", np.mean(grades))
print("Original class average:", original_class_average)


1. Student averages: [86.25 81.25 93.5  68.75 87.  ]
2. Highest grade per assignment: [95 93 91 97]
3. Average per assignment: [79.6 85.4 83.2 85.2]
4. Student with highest average: 3
Highest average: 93.5
5. Grades below 70: [60 68]
6. Grades after replacement:
 [[85 90 78 92]
 [70 88 91 76]
 [95 93 89 97]
 [70 72 70 75]
 [88 84 90 86]]
7. Overall class average after replacement: 83.95
Original class average: 83.35


---
## Short Questions

Answer in your own words:
1.	What is the difference between shape, size, and ndim?
2.	What is the difference between element-wise multiplication and matrix multiplication?
3.	What does axis=0 mean for a two-dimensional array?
4.	What does axis=1 mean?
5.	Why is NumPy useful for machine learning and deep learning?

1. `shape` gives the length of each axis, `size` gives the total number of entries, and `ndim` gives the number of axes. A 3 by 4 array has shape `(3, 4)`, size 12, and ndim 2.
2. Element-wise multiplication multiplies matching entries. Matrix multiplication computes each result entry by multiplying and adding a row of the first matrix with a column of the second matrix.
3. `axis=0` reduces down the rows, producing one result for each column.
4. `axis=1` reduces across the columns, producing one result for each row.
5. NumPy stores numerical data in arrays and performs efficient array and linear algebra operations. This makes it useful for preparing datasets and doing the calculations used in machine learning and deep learning.


---
## Challenge Problem

Create a random 5 × 5 matrix containing integers from 1 to 100.

Using NumPy only:
1.	Find the largest value.
2.	Find the smallest value.
3.	Calculate the mean.
4.	Calculate the standard deviation.
5.	Find all values greater than the mean.
6.	Replace all values below the mean with 0.
7.	Calculate the sum of each row and each column.

In [14]:
challenge_rng = np.random.default_rng(42)
matrix = challenge_rng.integers(1, 101, size=(5, 5))
print("Original random matrix:\n", matrix)
mean = np.mean(matrix)
print("1. Largest value:", np.max(matrix))
print("2. Smallest value:", np.min(matrix))
print("3. Mean:", mean)
print("4. Standard deviation:", np.std(matrix))
print("5. Values greater than the original mean:", matrix[matrix > mean])

matrix[matrix < mean] = 0
print("6. Values below the mean replaced with zero:\n", matrix)
print("7. Row sums after replacement:", np.sum(matrix, axis=1))
print("Column sums after replacement:", np.sum(matrix, axis=0))


Original random matrix:
 [[ 9 78 66 44 44]
 [86  9 70 21 10]
 [53 98 74 77 72]
 [79 52 13 84 46]
 [51 38 19 93 79]]
1. Largest value: 98
2. Smallest value: 9
3. Mean: 54.6
4. Standard deviation: 27.832355272236665
5. Values greater than the original mean: [78 66 86 70 98 74 77 72 79 84 93 79]
6. Values below the mean replaced with zero:
 [[ 0 78 66  0  0]
 [86  0 70  0  0]
 [ 0 98 74 77 72]
 [79  0  0 84  0]
 [ 0  0  0 93 79]]
7. Row sums after replacement: [144 156 321 163 172]
Column sums after replacement: [165 176 210 254 151]
