# Assignment 2 — PyTorch Tensors and Automatic Differentiation
#### Objective

Practice working with PyTorch tensors, including tensor creation, tensor properties, indexing, slicing, arithmetic, matrix operations, NumPy conversion, GPU awareness, and automatic differentiation.

The assignment follows the concepts demonstrated in the provided PyTorch notebook, including tensor dtype, shape, number of elements, dimensions, GPU availability, requires_grad, backward(), and NumPy/tensor conversion.

---

Instructions

Use PyTorch for all tensor operations.

Begin your notebook with:
```python
import torch
import numpy as np
```

Do not use TensorFlow for this assignment.

For each problem:

* Include your Python code.
* Display the output.
* Add explanations where requested.
* Your notebook should run from beginning to end without errors.

---

#### Part 1 — Creating Tensors

Create the following PyTorch tensors:

1. Scalar


In [1]:
%pip install torch numpy

import torch
import numpy as np

scalar = torch.tensor(5)
print(scalar)


   ---------------------------------------- 0.0/124.1 MB ? eta -:--:--
    --------------------------------------- 2.1/124.1 MB 11.6 MB/s eta 0:00:11
   - -------------------------------------- 4.7/124.1 MB 11.6 MB/s eta 0:00:11
   -- ------------------------------------- 7.1/124.1 MB 11.6 MB/s eta 0:00:11
   --- ------------------------------------ 9.4/124.1 MB 11.6 MB/s eta 0:00:10
   --- ------------------------------------ 11.8/124.1 MB 11.6 MB/s eta 0:00:10
   ---- ----------------------------------- 14.2/124.1 MB 11.6 MB/s eta 0:00:10
   ----- ---------------------------------- 16.5/124.1 MB 11.6 MB/s eta 0:00:10
   ----- ---------------------------------- 18.6/124.1 MB 11.4 MB/s eta 0:00:10
   ------ --------------------------------- 20.7/124.1 MB 11.3 MB/s eta 0:00:10
   ------- -------------------------------- 23.1/124.1 MB 11.3 MB/s eta 0:00:09
   -------- ------------------------------- 25.4/124.1 MB 11.3 MB/s eta 0:00:09
   -------- ------------------------------- 26.5/124.

2. Floating-point scalar

In [2]:
float_scalar = torch.tensor(5.0)
print(float_scalar)
print("Data type:", float_scalar.dtype)


tensor(5.)
Data type: torch.float32


3. Vector

In [3]:
vector = torch.tensor([1, 2, 3, 4, 5])
print(vector)


tensor([1, 2, 3, 4, 5])


4. Matrix

Create:
```python
[[1, 2, 3],
 [4, 5, 6]]
```

In [4]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Matrix from the question:\n", matrix)

todo_matrix = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("Alternative matrix from the TODO:\n", todo_matrix)


Matrix from the question:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Alternative matrix from the TODO:
 tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])


5. Three-dimensional tensor

Create a tensor with shape: 3 × 2 × 2

In [5]:
tensor_3d = torch.arange(1, 13).reshape(3, 2, 2)
print(tensor_3d)
print("Shape:", tensor_3d.shape)


tensor([[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]])
Shape: torch.Size([3, 2, 2])


---

#### Part 2 — Tensor Properties

Create:
```python
x = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])
```

In [6]:
x = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
print(x)


tensor([[1., 2., 3.],
        [4., 5., 6.]])


Determine:

* Its shape
* Number of dimensions
* Number of elements
* Data type

In [7]:
print("Shape:", x.shape)
print("Number of dimensions:", x.ndim)
print("Number of elements:", x.numel())
print("Data type:", x.dtype)


Shape: torch.Size([2, 3])
Number of dimensions: 2
Number of elements: 6
Data type: torch.float32


Question 1

What is the difference between:

* shape
* ndim
* numel()
* dtype

`shape` lists the length of each axis, `ndim` counts the axes, `numel()` counts all entries, and `dtype` identifies how each entry is stored, such as `torch.float32` or `torch.int64`.


Question 2

Why does the tensor have:
```python
2 dimensions
6 elements
```
even though its shape is: (2, 3)

---

The tensor has two axes: rows and columns. Its shape `(2, 3)` means it has 2 rows and 3 columns, so it has 2 dimensions and 2 × 3 = 6 elements.


#### Part 3 — Creating Special Tensors

Using PyTorch, create and display:

1. Zeros

A 2 × 3 tensor containing zeros.

In [8]:
print(torch.zeros((2, 3)))


tensor([[0., 0., 0.],
        [0., 0., 0.]])


2. Ones

A 3 × 3 tensor containing ones.

In [9]:
print(torch.ones((3, 3)))


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


3. Identity matrix

In [10]:
print(torch.eye(4))


tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


4. Range

Create a tensor containing:

0, 1, 2, 3, ..., 9

In [11]:
print(torch.arange(10))


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


5. Random tensor

Create a 3 × 3 tensor containing random values between 0 and 1.

In [12]:
torch.manual_seed(42)
print(torch.rand((3, 3)))


tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


---
#### Part 4 — Indexing and Slicing

Create:
```python
x = torch.tensor([[10, 20, 30, 40],
                  [50, 60, 70, 80],
                  [90, 100, 110, 120]])
```
Using PyTorch indexing and slicing:


In [13]:
x = torch.tensor([[10, 20, 30, 40],
                  [50, 60, 70, 80],
                  [90, 100, 110, 120]])
print(x[1, 2])


tensor(70)


In [14]:
print(x[0, :])


tensor([10, 20, 30, 40])


In [15]:
print(x[-1, :])


tensor([ 90, 100, 110, 120])


In [16]:
print(x[:, 1])


tensor([ 20,  60, 100])


In [17]:
print(x[-2:, :])


tensor([[ 50,  60,  70,  80],
        [ 90, 100, 110, 120]])


In [18]:
print(x[:, :3])


tensor([[ 10,  20,  30],
        [ 50,  60,  70],
        [ 90, 100, 110]])


In [19]:
print(x[1:3, 1:3])


tensor([[ 60,  70],
        [100, 110]])


Question

Explain how PyTorch tensor indexing is similar to NumPy array indexing.

Both use zero-based indices, with the row index before the column index. Both support negative indices and slices written as `start:stop:step`, where the stop index is excluded. For example, `x[1:3, 1:3]` selects the same part of a tensor or a NumPy array.


---
#### Part 5 — Tensor Arithmetic

Create:
```python
A = torch.tensor([[1., 2.],
                  [3., 4.]])

B = torch.tensor([[5., 6.],
                  [7., 8.]])
```

In [20]:
A = torch.tensor([[1., 2.], [3., 4.]])
B = torch.tensor([[5., 6.], [7., 8.]])
print(A + B)


tensor([[ 6.,  8.],
        [10., 12.]])


In [21]:
print(A - B)


tensor([[-4., -4.],
        [-4., -4.]])


In [22]:
print(A * B)


tensor([[ 5., 12.],
        [21., 32.]])


In [23]:
print(A / B)


tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])


In [24]:
print(A ** 2)


tensor([[ 1.,  4.],
        [ 9., 16.]])


In [25]:
print(torch.sqrt(A))


tensor([[1.0000, 1.4142],
        [1.7321, 2.0000]])


7. Matrix multiplication

In [26]:
product_at = A @ B
product_matmul = torch.matmul(A, B)
print("A @ B:\n", product_at)
print("torch.matmul(A, B):\n", product_matmul)
print("Results identical:", torch.equal(product_at, product_matmul))


A @ B:
 tensor([[19., 22.],
        [43., 50.]])
torch.matmul(A, B):
 tensor([[19., 22.],
        [43., 50.]])
Results identical: True


Question

Explain the difference between:
```python
A * B
and:
A @ B
```

`A * B` multiplies matching entries independently. `A @ B` performs matrix multiplication: each output entry is the sum of products of a row of A and a column of B. Here `A * B` is `[[5, 12], [21, 32]]`, while `A @ B` is `[[19, 22], [43, 50]]`.


---

Part 6 — Matrix Operations and Reductions

Create:
```python
A = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.]])

Perform the following operations.
```
1. Transpose

In [27]:
A = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
print(A.T)


tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [ ]:
print(torch.sum(A, dim=0))


tensor([5., 7., 9.])


In [ ]:
print(torch.sum(A, dim=1))


tensor([ 6., 15.])


In [30]:
print(torch.mean(A))


tensor(3.5000)


In [31]:
print(torch.max(A))


tensor(6.)


In [32]:
print(torch.min(A))


tensor(1.)


In [ ]:
print("Sample standard deviation:", torch.std(A))

print("Population standard deviation:", torch.std(A, correction=0))


Sample standard deviation: tensor(1.8708)
Population standard deviation: tensor(1.7078)


Questions

Explain:

* What does dim=0 mean?
* What does dim=1 mean?
* Why does reducing along a dimension change the shape of the tensor?

- `dim=0` reduces down the rows, leaving one result per column.
- `dim=1` reduces across the columns, leaving one result per row.
- A reduction combines all entries along the selected dimension. By default, that dimension is removed: summing a `(2, 3)` tensor over dim 0 gives shape `(3,)`, and over dim 1 gives shape `(2,)`. `keepdim=True` keeps the reduced dimension with length 1.


---
Part 7 — NumPy ↔ PyTorch

Create the following NumPy array:
```python
a = np.array([[1., 2.],
              [3., 4.]])
```

In [ ]:
a = np.array([[1., 2.], [3., 4.]])
A = torch.from_numpy(a)
print(A)


tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [35]:
print("Tensor A:\n", A)
print("Shape:", A.shape)
print("Data type:", A.dtype)


Tensor A:
 tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
Shape: torch.Size([2, 2])
Data type: torch.float64


In [ ]:
A = A + 10
print(A)


tensor([[11., 12.],
        [13., 14.]], dtype=torch.float64)


In [ ]:
converted_array = A.detach().cpu().numpy()
print(converted_array)


[[11. 12.]
 [13. 14.]]


In [38]:
print("Type:", type(converted_array))
print("Is a NumPy array:", isinstance(converted_array, np.ndarray))


Type: <class 'numpy.ndarray'>
Is a NumPy array: True


---
Part 8 — GPU Awareness

In [39]:
gpu_available = torch.cuda.is_available()
print("CUDA GPU available:", gpu_available)


CUDA GPU available: False


In [ ]:
device = torch.device("cuda" if gpu_available else "cpu")
print("Selected device:", device)


Selected device: cpu


In [41]:
x = torch.tensor([[1., 2.], [3., 4.]])
x = x.to(device)
print(x)
print("Tensor device:", x.device)


tensor([[1., 2.],
        [3., 4.]])
Tensor device: cpu


Questions
* What device is your tensor using?
* What is the difference between CPU and GPU computation?
* Why are GPUs useful for deep learning?
* What happens if CUDA is not available?

- The tensor uses the device printed by `x.device`. This code selects CUDA when available and otherwise selects CPU; rerunning the notebook checks the current machine.
- A CPU is suited to general-purpose tasks, while a GPU can perform many numerical operations in parallel. For small tasks, GPU transfer and setup costs can outweigh the benefit.
- Deep learning uses large matrix operations that GPUs can perform in parallel, which can speed up training and inference.
- If CUDA is unavailable, this code falls back to CPU and still runs.


---
Part 9 — Automatic Differentiation

PyTorch provides automatic differentiation using autograd.

In [ ]:
x = torch.tensor([[1., 2.], [3., 4.]], requires_grad=True)
y = 3 * x ** 2 + 2
print("y:\n", y)


y:
 tensor([[ 5., 14.],
        [29., 50.]], grad_fn=<AddBackward0>)


In [ ]:
z = torch.sum(y)
z.backward()
print("y:\n", y)
print("z:", z)
print("x.grad:\n", x.grad)
print("Gradient matches 6x:", torch.allclose(x.grad, 6 * x.detach()))


y:
 tensor([[ 5., 14.],
        [29., 50.]], grad_fn=<AddBackward0>)
z: tensor(98., grad_fn=<SumBackward0>)
x.grad:
 tensor([[ 6., 12.],
        [18., 24.]])
Gradient matches 6x: True


Questions
* What does requires_grad=True mean?
* What does backward() do?
* What is stored in x.grad?
* Why is automatic differentiation important for neural networks?

- `requires_grad=True` tells PyTorch to track operations involving this tensor so it can calculate derivatives.
- `backward()` applies the chain rule through the computation graph and accumulates gradients in leaf tensors. Here z is scalar, so no explicit starting gradient is needed.
- `x.grad` stores the derivative of z with respect to each entry of x. Since z is the sum of `3x² + 2`, its gradient is `6x`, giving `[[6, 12], [18, 24]]`.
- Neural networks need gradients of the loss with respect to their parameters. Automatic differentiation calculates those gradients so an optimizer can update the parameters without manually deriving every derivative.
